import Link from "next/link";

const pages: Record<string, { eyebrow: string; title: string; intro: string; items: { title: string; text: string }[] }> = {
  menu: { eyebrow: "02 / The menu", title: "Made slowly.\nServed beautifully.", intro: "A seasonal Italian menu built around handmade pasta, fire, produce and the quiet details that make a meal memorable.", items: [{ title: "Tagliatelle al Ragù", text: "Hand-cut pasta, twelve-hour beef ragù, Parmigiano Reggiano." }, { title: "Branzino", text: "Charcoal-grilled sea bass, lemon, fennel and olive oil." }, { title: "Tiramisù Borcelle", text: "Mascarpone, espresso, cocoa and a touch of dark chocolate." }] },
  story: { eyebrow: "03 / Our story", title: "Tradition,\nwithout nostalgia.", intro: "Borcelle takes the rituals of an Italian osteria and gives them a modern, cinematic home.", items: [{ title: "The table", text: "An intimate room where long lunches become late evenings." }, { title: "The craft", text: "Pasta is rolled by hand. Sauces are given time. Nothing is rushed." }, { title: "The philosophy", text: "Fewer ingredients. Better ingredients. More intention." }] },
  chef: { eyebrow: "04 / The chef", title: "The hands\nbehind the table.", intro: "Our kitchen is led by a belief that technique should make ingredients feel more alive, never more complicated.", items: [{ title: "Season first", text: "The menu changes with what the market gives us." }, { title: "Fire & time", text: "Slow sauces, live fire and patient preparation define the kitchen." }, { title: "Italian soul", text: "Classic foundations, interpreted with a contemporary eye." }] },
  wine: { eyebrow: "05 / The cellar", title: "Wine with\nintention.", intro: "A compact cellar of Italian bottles chosen for character, balance and the stories they bring to the table.", items: [{ title: "Barolo", text: "Elegant Nebbiolo with depth, perfume and structure." }, { title: "Brunello", text: "Sangiovese with earth, red fruit and a long finish." }, { title: "Etna Rosso", text: "Volcanic, mineral and beautifully bright." }] },
  gallery: { eyebrow: "06 / The gallery", title: "A night worth\nremembering.", intro: "A visual diary of pasta, fire, wine and the atmosphere between the courses.", items: [{ title: "The kitchen", text: "Hands at work, flames rising, pasta moving through the room." }, { title: "The table", text: "Glass, linen, candlelight and the first pour." }, { title: "The details", text: "The small gestures that turn dinner into an experience." }] },
  contact: { eyebrow: "08 / Contact", title: "Come find\nus.", intro: "For private dining, celebrations or simply a table for tonight, our team is ready.", items: [{ title: "Address", text: "Via Borcelle 17 · Milano, Italia" }, { title: "Hours", text: "Tuesday–Sunday · 18:00–23:30" }, { title: "Reservations", text: "Tables are released daily for the evening service." }] },
};

export default async function InteriorPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug === "reservations") {
    return <main className="min-h-screen bg-black px-6 py-32 text-white md:px-12"><div className="mx-auto max-w-4xl"><Link href="/" className="text-[9px] uppercase tracking-[.35em] text-[#c9a96a]">← Osteria Borcelle</Link><p className="mt-24 text-[9px] uppercase tracking-[.45em] text-[#c9a96a]">Reservations</p><h1 className="mt-6 font-display text-6xl leading-[.9] md:text-[9rem]">Your table<br /><em className="text-[#c9a96a]">awaits.</em></h1><form className="mt-16 grid gap-5 rounded-[2rem] border border-white/10 bg-white/[.025] p-6 md:grid-cols-2 md:p-10"><input required placeholder="Name" className="border-b border-white/15 bg-transparent px-1 py-4 outline-none placeholder:text-white/25" /><input required type="email" placeholder="Email" className="border-b border-white/15 bg-transparent px-1 py-4 outline-none placeholder:text-white/25" /><input required type="date" className="border-b border-white/15 bg-transparent px-1 py-4 text-white/60 outline-none" /><select className="border-b border-white/15 bg-transparent px-1 py-4 text-white/60 outline-none"><option className="bg-black">2 guests</option><option className="bg-black">3 guests</option><option className="bg-black">4 guests</option><option className="bg-black">6 guests</option></select><button type="submit" className="rounded-full border border-[#c9a96a]/60 px-7 py-4 text-[9px] uppercase tracking-[.3em] text-[#ead19a] transition hover:bg-[#ead19a] hover:text-black md:col-span-2">Request a table</button></form></div></main>;
  }
  const page = pages[slug] ?? pages.contact;
  return <main className="min-h-screen bg-black px-6 py-32 text-white md:px-12"><div className="mx-auto max-w-7xl"><Link href="/" className="text-[9px] uppercase tracking-[.35em] text-[#c9a96a]">← Osteria Borcelle</Link><div className="mt-24 max-w-5xl"><p className="text-[9px] uppercase tracking-[.45em] text-[#c9a96a]">{page.eyebrow}</p><h1 className="mt-7 whitespace-pre-line font-display text-6xl leading-[.87] md:text-[9rem]">{page.title}</h1><p className="mt-10 max-w-2xl text-sm leading-8 text-white/45">{page.intro}</p></div><div className="mt-24 grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-3">{page.items.map((item, i) => <article key={item.title} className="bg-[#070707] p-8 md:min-h-72"><span className="text-[8px] text-[#c9a96a]">0{i + 1}</span><h2 className="mt-16 font-display text-3xl">{item.title}</h2><p className="mt-4 text-sm leading-7 text-white/35">{item.text}</p></article>)}</div><Link href="/reservations" className="mt-12 inline-flex rounded-full border border-[#c9a96a]/50 px-7 py-4 text-[9px] uppercase tracking-[.3em] text-[#ead19a] transition hover:bg-[#ead19a] hover:text-black">Reserve a table</Link></div></main>;
}
